application: rhythmludus
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /script
  static_dir: static/script
- url: /song
  static_dir: static/songs
- url: /rhythms
  static_dir: static/rhythm_xmls
- url: /sound
  static_dir: static/audioRessource/instrument
- url: /backgroundsong
  static_dir: static/audioRessource/backgroundsong
- url: /style
  static_dir: static/style
- url: /images
  static_dir: static/images

- url: /.*
  script: main.app




libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
