application: rhythmludus
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /script
  static_dir: static/script
- url: /song
  static_dir: static/songs
- url: /sound
  static_dir: static/audioRessource
- url: /style
  static_dir: static/style

- url: /.*
  script: main.app




libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
